### ISSUE TITLE
Software: http-server updates wrong GUI widget

### ISSUE THREAD

**Issue by nic-str** [kit-adl/astropix#2]
For unused DACs, a parameter is created but no widget. Therefore the http-server updates the correct parameter, but updates a wrong widget in GUI.
https://github.com/kit-adl/astropix/blob/54e5a5cfb669cc525a37813c6cdf72cd374ce2f9/Astropix_v1_202004/Apix_v1_Software/main.cpp#L119-L123

Example:
http://localhost:8090/asic/config/DACS/ithres_unused/set/10 updates vn1 to 10 in the GUI

**Comment by richnou** [comment]
Well seen, will fix
